// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Modifier struct {
	Name     string `json:"Name"`
	Contents string `json:"Contents"`
}

type NewModifier struct {
	Name     string `json:"Name"`
	Contents string `json:"Contents"`
}

type NewProvince struct {
	ID        string         `json:"Id"`
	Name      string         `json:"Name"`
	Modifiers []*NewModifier `json:"Modifiers"`
}

type Province struct {
	ID        string      `json:"Id"`
	Name      string      `json:"Name"`
	Modifiers []*Modifier `json:"Modifiers"`
}
